# Generated by Django 2.1.1 on 2018-12-16 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('college_id', models.AutoField(primary_key=True, serialize=False)),
                ('college_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'College Name',
                'verbose_name_plural': 'College Name',
                'db_table': 'College',
                'ordering': ['college_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('player_height', models.FloatField(blank=True, null=True)),
                ('player_weight', models.FloatField(blank=True, null=True)),
                ('player_birth_year', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Player',
                'db_table': 'Player',
                'ordering': ['player_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('season_id', models.AutoField(primary_key=True, serialize=False)),
                ('season_year', models.IntegerField(unique=True)),
                ('season_game', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Season Year and Season Games',
                'verbose_name_plural': 'Season Year and Season Games',
                'db_table': 'Season',
                'ordering': ['season_year'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SeasonPlayer',
            fields=[
                ('season_player_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_age', models.IntegerField(blank=True, null=True)),
                ('player_games', models.IntegerField(blank=True, null=True)),
                ('player_minutes', models.IntegerField(blank=True, null=True)),
                ('player_per', models.DecimalField(blank=True, db_column='player_PER', decimal_places=1, max_digits=10, null=True)),
                ('player_ts', models.DecimalField(blank=True, db_column='player_TS', decimal_places=3, max_digits=10, null=True)),
                ('player_ows', models.DecimalField(blank=True, db_column='player_OWS', decimal_places=1, max_digits=10, null=True)),
                ('player_dws', models.DecimalField(blank=True, db_column='player_DWS', decimal_places=1, max_digits=10, null=True)),
                ('player_ws', models.DecimalField(blank=True, db_column='player_WS', decimal_places=1, max_digits=10, null=True)),
                ('player_ws_per', models.DecimalField(blank=True, db_column='player_WS_per', decimal_places=3, max_digits=10, null=True)),
                ('player_fg', models.IntegerField(blank=True, db_column='player_FG', null=True)),
                ('player_fgp', models.DecimalField(blank=True, db_column='player_FGP', decimal_places=3, max_digits=10, null=True)),
                ('player_three_fg', models.DecimalField(blank=True, db_column='player_three_FG', decimal_places=0, max_digits=10, null=True)),
                ('player_three_fgp', models.DecimalField(blank=True, db_column='player_three_FGP', decimal_places=3, max_digits=10, null=True)),
                ('player_trb', models.IntegerField(blank=True, db_column='player_TRB', null=True)),
                ('player_ast', models.IntegerField(blank=True, db_column='player_AST', null=True)),
                ('player_stl', models.IntegerField(blank=True, db_column='player_STL', null=True)),
                ('player_blk', models.IntegerField(blank=True, db_column='player_BLK', null=True)),
                ('player_tov', models.IntegerField(blank=True, db_column='player_TOV', null=True)),
                ('player_pf', models.IntegerField(blank=True, db_column='player_PF', null=True)),
                ('player_pts', models.IntegerField(blank=True, db_column='player_PTS', null=True)),
            ],
            options={
                'verbose_name': 'Performance on Season Player',
                'verbose_name_plural': 'Performance on Season Player',
                'db_table': 'Season_Player',
                'ordering': ['player', 'team', 'season'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='StateCountry',
            fields=[
                ('state_country_id', models.AutoField(primary_key=True, serialize=False)),
                ('state_country_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'State or Country',
                'verbose_name_plural': 'State or Country',
                'db_table': 'State_Country',
                'ordering': ['state_country_name'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('team_id', models.AutoField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Team',
                'db_table': 'Team',
                'ordering': ['team_name'],
                'managed': False,
            },
        ),
    ]
