# Generated by Django 2.1.1 on 2018-12-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nba_stats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='college',
            table='college',
        ),
        migrations.AlterModelTable(
            name='player',
            table='player',
        ),
        migrations.AlterModelTable(
            name='season',
            table='season',
        ),
        migrations.AlterModelTable(
            name='seasonplayer',
            table='season_player',
        ),
        migrations.AlterModelTable(
            name='statecountry',
            table='state_country',
        ),
        migrations.AlterModelTable(
            name='team',
            table='team',
        ),
    ]
